name: signal_protocol_flutter
description: "A production-ready Dart package providing Signal Protocol encryption/decryption capabilities with persistent storage and Firebase-based key management."
version: 0.0.1
homepage: https://github.com/stdNullPtr/signal-protocol-flutter
repository: https://github.com/stdNullPtr/signal-protocol-flutter
issue_tracker: https://github.com/stdNullPtr/signal-protocol-flutter/issues

environment:
  sdk: ^3.7.2
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  libsignal_protocol_dart: ^0.7.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  firebase_database: ^10.5.0
  firebase_core: ^2.24.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  hive_test: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
